sudo: required. 

services:
    - docker

before_install:
    - docker build -t johnmatthewd/client_test -f ./client/Dockerfile.dev ./client
    - docker build -t johnmatthewd/nginx_test -f ./nginx/Dockerfile.dev ./nginx
    #- docker build -t johnmatthewd/server_test -f ./server/Dockerfile.dev ./server
    #- docker build -t johnmatthewd/worker_test -f ./worker/Dockerfile.dev ./worker

script:
    - docker run -e CI=true johnmatthewd/client_test npm run test
    #- docker run -e CI=true johnmatthewd/nginx_test nginx -t
    #- docker run -e CI=true johnmatthewd/server_test npm run test
    #- docker run -e CI=true johnmatthewd/worker_test npm run test

after_success:
    - docker build -t johnmatthewd/client-p ./client 
    - docker build -t johnmatthewd/nginx-p ./nginx
   # - docker build -t johnmatthewd/server-p ./server
   # - docker build -t johnmatthewd/worker-p ./worker
    
    #Push the images to docker-hub
    #step 1 login to docker cli
    